
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: ffweb
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./secret:/var/www/inc
    depends_on:
      - db
    networks:
      - ffnetwork

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: ffdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ff_root
      MYSQL_DATABASE: ffdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ffdb:/var/lib/mysql
    networks:
      - ffnetwork

  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
      dockerfile: Dockerfile
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ff_root
    depends_on:
      - db
    networks:
      - ffnetwork

volumes:
  ffdb:

networks:
  ffnetwork:
